### ISSUE TITLE
Dokumentacja kodu

### ISSUE THREAD

**Issue by DawidMichalak** [Endrju00/JSON-tools#11]
>Dokumentacja generuje się w sposób automatyczny podczas budowy oprogramowania

## Zadania
- [x] Dokumentacja generuje się w sposób automatyczny
- [x] Przynajmniej 1 klasa / interfejs posiada pełną dokumentację techniczną* (javadoc, itp.)

**Comment by wiktoriakeller** [comment]
Dodano dokumentację techniczną (javadoc) dla przynajmniej 3 klas.
