### ISSUE TITLE
Uzyskanie struktury w formacie JSON zawierającej określone własności

### ISSUE THREAD

**Issue by Endrju00** [Endrju00/JSON-tools#4]
>Jako programista mogę uzyskać strukturę w formacie JSON zawierającą tylko określone własności, aby uprościć strukturę

## Kryteria akceptacji
* Kształt danych nie ulega zmianie
* Z obiektów JSON usuwane są wszystkie własności poza tymi przekazanymi na wejściu
* Zgłoszenie błędu dla niepoprawnego JSON-a

## Zadania
- [ ] Podzielenie struktury na określone własności
- [ ] *Do uzupełnienia*

## Przydatne materiały
* *Do uzupełnienia*

**Comment by joj4z** [comment]
robie
