### ISSUE TITLE
Uzyskanie struktury w formacie JSON nie zawierającej określonych własności

### ISSUE THREAD

**Issue by Endrju00** [Endrju00/JSON-tools#5]
>Jako programista mogę uzyskać strukturę w formacie JSON nie zawierającą określonych własności, aby uprościć strukturę

## Kryteria akceptacji
* Kształt danych nie ulega zmianie
* Obiekty JSON posiadają tylko wybrane własności (wszystkie inne są usuwane)
* Zgłoszenie błędu dla niepoprawnego JSON-a

## Zadania 
- [ ] *Do uzupełnienia*

## Przydatne materiały
* *Do uzupełnienia*

**Comment by joj4z** [comment]
robie
