### ISSUE TITLE
Oznaczenia wersji

### ISSUE THREAD

**Issue by DawidMichalak** [Endrju00/JSON-tools#8]
>Kod określający inkrement produktu jest oznaczony w repozytorium (tag = numer wersji) oraz odpowiednia wersja w pom.xml.

## Zadania
- [x] Oznaczenie w repozytorium
- [x] Oznaczenie w  pom.xml

**Comment by wiktoriakeller** [comment]
Dodano oznaczanie wersji w pom.xml oraz repozytorium.
